---
version: "3.8"


services:

  redis:
    image: redis:latest
    # build:
    #   context: .
    #   dockerfile: base.Dockerfile
    container_name: redis
    hostname: redis
    networks: 
      - main-network
    ports:
      - target: 6379
        published: 6379
        mode: host
    volumes:
      - type: volume
        source: redis-volume
        target: /data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 30s
      retries: 50
    restart: always


networks:
  main-network:
    name: main-network
    external: false
    driver: bridge
    attachable: false


volumes:
  redis-volume:
